[project]
name = "langgraph-rag-about-myself"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "chainlit>=2.10.0",
    "fastapi>=0.135.1",
    "langchain>=1.2.10",
    "langchain-groq>=1.1.2",
    "langchain-huggingface>=1.2.1",
    "langchain-pinecone>=0.2.13",
    "langchain-text-splitters>=1.1.1",
    "langgraph>=1.0.10",
    "langsmith>=0.7.16",
    "pinecone>=6.0.0,<8.0.0",
    "python-dotenv>=1.0.0",
    "sentence-transformers>=5.2.3",
    "tiktoken>=0.12.0",
    "uvicorn>=0.41.0",
]

[tool.uv]
override-dependencies = [
    "pinecone-plugin-inference>=0.0.0; python_version < '0'",
]
